version: '3.8'

services:
  # Frontend Service - Production Overrides
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    volumes:
      - frontend_logs:/var/log/nginx
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Backend Service - Production Overrides
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # PostgreSQL Service - Production Overrides
  postgres:
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - grocery-network

volumes:
  postgres_data:
  backend_logs:
  backend_uploads:
  frontend_logs:
  nginx_logs:

networks:
  grocery-network:
    driver: bridge